require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::BankAccountsController do 

  let(:o) {Organism.create!(title: 'TEST')}
  # This should return the minimal set of attributes required to create a valid
  # bank_account. As you add validations to bank_account, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {name: 'CrediX', number: '5555', organism_id: o.id}
  end

  describe "GET index" do
    it "assigns all bank_accounts as @bank_accounts" do
      ba = o.bank_accounts.create! valid_attributes
      get :index, :organism_id=>o.id.to_s
      assigns(:bank_accounts).should eq([ba])
    end
  end

  describe "GET show" do
    it "assigns the requested bank_account as @bank_account" do
      bank_account = o.bank_accounts.create! valid_attributes
      get :show, :organism_id=>o.id.to_s, :id => bank_account.id.to_s
      assigns(:bank_account).should eq(bank_account)
    end
  end

  describe "GET new" do
    it "assigns a new bank_account as @bank_account" do
      get :new,  :organism_id=>o.id.to_s
      assigns(:bank_account).should be_a_new(BankAccount) 
      assigns(:bank_account).organism.should == o 
    end
  end

  describe "GET edit" do 
    it "assigns the requested bank_account as @bank_account" do
      bank_account = o.bank_accounts.create! valid_attributes
      get :edit,organism_id:o.id.to_s, :id => bank_account.id.to_s
      assigns(:bank_account).should eq(bank_account)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new bank_account" do
        expect {
          post :create, :organism_id=>o.id.to_s, :bank_account => valid_attributes
        }.to change(BankAccount, :count).by(1)
      end

      it "assigns a newly created bank_account as @bank_account" do
        post :create, :organism_id=>o.id.to_s, :bank_account => valid_attributes
        assigns(:bank_account).should be_a(BankAccount)
        assigns(:bank_account).should be_persisted
      end

      it "redirects to the created bank_account" do
        post :create, :organism_id=>o.id.to_s,  :bank_account => valid_attributes
        response.should redirect_to(admin_organism_bank_accounts_url(o))
      end 
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bank_account as @bank_account" do
        # Trigger the behavior that occurs when invalid params are submitted
        BankAccount.any_instance.stub(:save).and_return(false)
        post :create, :organism_id=>o.id.to_s,  :bank_account => {}
        assigns(:bank_account).should be_a_new(BankAccount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BankAccount.any_instance.stub(:save).and_return(false)
        post :create,:organism_id=>o.id.to_s,  :bank_account => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bank_account" do
        bank_account = o.bank_accounts.create! valid_attributes
        # Assuming there are no other bank_accounts in the database, this
        # specifies that the bank_account created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BankAccount.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update,:organism_id=>o.id.to_s,  :id => bank_account.id, :bank_account => {'these' => 'params'}
      end

      it "assigns the requested bank_account as @bank_account" do
        bank_account = o.bank_accounts.create! valid_attributes
        put :update,:organism_id=>o.id.to_s,  :id => bank_account.id, :bank_account => valid_attributes
        assigns(:bank_account).should eq(bank_account)
      end

      it "redirects to the bank_account" do
        bank_account = o.bank_accounts.create! valid_attributes
        put :update, :organism_id=>o.id.to_s, :id => bank_account.id, :bank_account => valid_attributes
        response.should redirect_to(admin_organism_bank_accounts_url(o))
      end
    end

    describe "with invalid params" do
      it "assigns the bank_account as @bank_account" do
        bank_account = o.bank_accounts.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BankAccount.any_instance.stub(:save).and_return(false)
        put :update, :organism_id=>o.id.to_s, :id => bank_account.id.to_s, :bank_account => {}
        assigns(:bank_account).should eq(bank_account)
      end

      it "re-renders the 'edit' template" do
        bank_account = o.bank_accounts.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BankAccount.any_instance.stub(:save).and_return(false)
        put :update,:organism_id=>o.id.to_s,  :id => bank_account.id.to_s, :bank_account => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bank_account" do
      bank_account = o.bank_accounts.create! valid_attributes
      expect {
        delete :destroy,:organism_id=>o.id.to_s,  :id => bank_account.id.to_s
      }.to change(o.bank_accounts, :count).by(-1)
    end 

    it "redirects to the bank_accounts list" do
      bank_account = o.bank_accounts.create! valid_attributes
      delete :destroy,:organism_id=>o.id.to_s,  :id => bank_account.id.to_s
      response.should redirect_to(admin_organism_bank_accounts_url(o))
    end
  end

end
