# -*- encoding : utf-8 -*-

require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass. 
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message. 

RSpec.configure do |c|
  # c.filter = {:wip=> true }
end

describe Admin::RoomsController do
  include SpecControllerHelper
 
  def valid_attributes
    {database_name:'assotest4', user_id:@cu.to_param}
  end

  def user_session
    {user:@cu.id}
  end

  before(:each) do
    minimal_instances
    # minimal instance donne @cu pour current_user et @r comme room
  end

 
  describe "GET index" do
    
    it "assigns all rooms as @rs" do
      pending 'l action index n existe pas encore'
      get :index,{}, user_session
      assigns(:rooms).should eq([@r])
    end
  end

  describe "GET show" do
    it "assigns the requested room as @r" do
      @cu.should_receive(:rooms).and_return(@a = double(Arel))
      @a.should_receive(:find).with(@r.to_param).and_return(@r)
      get :show, {:id => @r.to_param}, user_session
      assigns(:room).should eq(@r)
    end
  end

#  describe "GET new" do
#    it "assigns a new user as @user" do
#      get :new
#      assigns(:user).should be_a_new(User)
#    end
#  end
#
#  describe "GET edit" do
#    it "assigns the requested user as @user" do
#      user = User.create! valid_attributes
#      get :edit, :id => user.id.to_s
#      assigns(:user).should eq(user)
#    end
#  end
#
#  describe "POST create" do
#    describe "with valid params" do
#      it "creates a new User" do
#        expect {
#          post :create, :user => valid_attributes
#        }.to change(User, :count).by(1)
#      end
#
#      it "assigns a newly created user as @user" do
#        post :create, :user => valid_attributes
#        assigns(:user).should be_a(User)
#        assigns(:user).should be_persisted
#      end
#
#      it "redirects to the created user" do
#        post :create, :user => valid_attributes
#        response.should redirect_to(new_admin_organism_path)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns a newly created but unsaved user as @user" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        User.any_instance.stub(:save).and_return(false)
#        post :create, :user => {}
#        assigns(:user).should be_a_new(User)
#      end
#
#      it "re-renders the 'new' template" do
#        # Trigger the behavior that occurs when invalid params are submitted
#        User.any_instance.stub(:save).and_return(false)
#        post :create, :user => {}
#        response.should render_template("new")
#      end
#    end
#  end
#
#  describe "PUT update" do
#    describe "with valid params" do
#      it "updates the requested user" do
#        user = User.create! valid_attributes
#        # Assuming there are no other users in the database, this
#        # specifies that the User created on the previous line
#        # receives the :update_attributes message with whatever params are
#        # submitted in the request.
#        User.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#        put :update, :id => user.id, :user => {'these' => 'params'}
#      end
#
#      it "assigns the requested user as @user" do
#        user = User.create! valid_attributes
#        put :update, :id => user.id, :user => valid_attributes
#        assigns(:user).should eq(user)
#      end
#
#      it "redirects to the user" do
#        user = User.create! valid_attributes
#        put :update, :id => user.id, :user => valid_attributes
#        response.should redirect_to(user)
#      end
#    end
#
#    describe "with invalid params" do
#      it "assigns the user as @user" do
#        user = User.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        User.any_instance.stub(:save).and_return(false)
#        put :update, :id => user.id.to_s, :user => {}
#        assigns(:user).should eq(user)
#      end
#
#      it "re-renders the 'edit' template" do
#        user = User.create! valid_attributes
#        # Trigger the behavior that occurs when invalid params are submitted
#        User.any_instance.stub(:save).and_return(false)
#        put :update, :id => user.id.to_s, :user => {}
#        response.should render_template("edit")
#      end
#    end
#  end

  describe "DELETE destroy" do
    before(:each) do
      @cu.stub_chain(:rooms, :find).and_return(@r)
      @r.stub(:db_filename).and_return('assotest1.sqlite3')
      @r.stub(:absolute_db_name).and_return(File.join(Rails.root,'db', Rails.env, 'organisms', 'assotest1.sqlite3'))
    end

    it "destroys the requested room" do
      @r.stub(:destroy).and_return true
      File.should_receive(:exist?).with(@r.absolute_db_name).and_return true
      File.should_receive(:delete).with(@r.absolute_db_name)
      delete :destroy,{:id => @r.to_param}, user_session 
    end 

    
  end

end
